# Generated by Django 5.2.3 on 2025-10-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_employee_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_job', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_model',
            name='department',
        ),
        migrations.AddField(
            model_name='employee_model',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.employee_job'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
