# Generated by Django 5.2.4 on 2025-10-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_department_student_model_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_id',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_id',
            name='studentid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='student_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentID', to='Student.student_id'),
        ),
    ]
