# Generated by Django 5.2.4 on 2025-11-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_student_id_id_alter_student_id_studentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.marks')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student_model')),
            ],
        ),
    ]
