# Generated by Django 5.2.4 on 2025-11-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_marks_student_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Marks_model',
        ),
    ]
