# Generated by Django 5.2.4 on 2025-11-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_rename_marks_marks_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_marks',
            name='std_marks',
        ),
        migrations.AddField(
            model_name='student_marks',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_marks',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Student.subjects'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marks_model',
        ),
    ]
