# Generated by Django 5.2.4 on 2025-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_subjects_remove_student_marks_std_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
