# Generated by Django 5.2.4 on 2025-11-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_student_marks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks',
            name='status',
        ),
    ]
