# Generated by Django 5.2.4 on 2025-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_remove_student_marks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
