# Generated by Django 5.2.4 on 2025-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_alter_student_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
