# Generated by Django 5.2.4 on 2025-11-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_alter_student_model_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_id',
            unique_together={('studentid',)},
        ),
        migrations.AlterUniqueTogether(
            name='student_marks',
            unique_together={('student_name', 'subject')},
        ),
    ]
