# Generated by Django 5.2.4 on 2025-11-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_alter_student_id_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_id',
            unique_together=set(),
        ),
    ]
