# Generated by Django 5.2.4 on 2025-11-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_alter_student_id_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_id',
            unique_together={('studentid',)},
        ),
    ]
