# Generated by Django 5.2.4 on 2025-11-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_alter_student_id_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_marks',
            unique_together=set(),
        ),
    ]
