# Generated by Django 5.2.3 on 2025-11-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_alter_student_marks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_marks',
            unique_together={('student_name', 'subject')},
        ),
    ]
